import CustomRollManager from "./CustomRollManager";
import DiceManager from "./DiceManager";
import DieSizeManager from "./DieSizeManager";
import ExpandedCategoryManager from "./ExpandedCategoryManager";
import ExpectedResultManager from "./ExpectedResultManager";
import HistoryManager from "./HistoryManager";
import RollManager from "./RollManager";
import RollResultVolumeManager from "./RollResultVolumeManager";
import ShakeEnabledManager from "./ShakeEnabledManager";
import ShakeSensitivityManager from "./ShakeSensitivityManager";
import ShakeVolumeManager from "./ShakeVolumeManager";
import SimpleRollPropertiesManager from "./SimpleRollPropertiesManager";
import SortTypeManager from "./SortTypeManager";
import TabManager from "./TabManager";
import ThemeManager from "./ThemeManager";
import LegacyMigrationManager from "./LegacyMigrationManager";
import ShakeLengthManager from "./ShakeLengthManager";
import ShakeDieSizeManager from "./ShakeDieSizeManager";
import AnimationsEnabledManager from "./AnimationsEnabledManager";

export function OpenAllSingletons() {
    AnimationsEnabledManager.getInstance();
    CustomRollManager.getInstance();
    DiceManager.getInstance();
    DieSizeManager.getInstance();
    ExpandedCategoryManager.getInstance();
    ExpectedResultManager.getInstance();
    LegacyMigrationManager.getInstance();
    HistoryManager.getInstance();
    RollManager.getInstance();
    RollResultVolumeManager.getInstance();
    ShakeDieSizeManager.getInstance();
    ShakeEnabledManager.getInstance();
    ShakeLengthManager.getInstance();
    ShakeSensitivityManager.getInstance();
    ShakeVolumeManager.getInstance();
    SimpleRollPropertiesManager.getInstance();
    SortTypeManager.getInstance();
    TabManager.getInstance();
    ThemeManager.getInstance();
}